pipeline {
    agent {
        docker {
            image 'maven:3.9.9-eclipse-temurin-21'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    options { skipStagesAfterUnstable() }

    stages {
        stage('Identify Committer') {
            steps {
                script {
                    def author = env.GIT_AUTHOR_NAME
                    def commit = env.GIT_COMMIT
                    def branch = env.GIT_BRANCH

                    echo "Triggered by: ${author}"
                    echo "Commit: ${commit}"
                    echo "Branch: ${branch}"

                    // Store it for later stages
                    currentBuild.description = "Pushed by ${author} on ${branch}"
                }
            }
        }
        stage('Build') {
            steps {
                dir('Inventory-manager') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('Inventory-manager') {
                    sh 'mvn test'
                }
            }
            post { always { junit 'Inventory-manager/target/surefire-reports/*.xml' } }
        }
    }
}