pipeline {
    agent {
        docker {
            image 'maven:3.9.9-eclipse-temurin-21'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    options { skipStagesAfterUnstable() }

    stages {
        stage('Identify Committer') {
            steps {
                script {
                    def commit = env.GIT_COMMIT
                    def branch = env.GIT_BRANCH
                    def author = sh(
                            script: "git log -1 --format='%an'",
                            returnStdout: true
                    ).trim()
                    def pusher = env.PUSHER_NAME?.trim()

                    def displayName = (author && author != '') ? author : pusher

                    echo "Triggered by: ${displayName}"
                    echo "Commit: ${commit}"
                    echo "Branch: ${branch}"

                    // Store it for later stages
                    currentBuild.description = "Pushed by ${displayName} on ${branch}"
                }
            }
        }
        stage('Build') {
            steps {
                dir('Inventory-manager') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('Inventory-manager') {
                    sh 'mvn test'
                }
            }
            post { always { junit 'Inventory-manager/target/surefire-reports/*.xml' } }
        }
    }
}