spring.application.name=Inventory-manager
spring.config.import=optional:classpath:secrets.properties
server.port=${PORT:9090}
logging.level.root=WARN
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
